# Utiliser une image JDK légère pour construire l'application
FROM eclipse-temurin:17-jdk-jammy AS build

# Définir le répertoire de travail
WORKDIR /app

# Copier le wrapper Maven et le fichier pom.xml
COPY mvnw .
COPY .mvn .mvn
COPY pom.xml .

# Télécharger les dépendances
RUN ./mvnw dependency:go-offline

# Copier le code source
COPY src ./src

# Construire l'application
RUN ./mvnw package -DskipTests

# Utiliser une image JRE plus petite pour le conteneur final
FROM eclipse-temurin:17-jre-jammy

# Définir le répertoire de travail
WORKDIR /app

# Copier le fichier jar construit depuis l'étape de construction
COPY --from=build /app/target/notes-api-0.0.1-SNAPSHOT.jar .

# Exposer le port sur lequel l'application s'exécute
EXPOSE 8080

# Lancer l'application
ENTRYPOINT ["java", "-jar", "notes-api-0.0.1-SNAPSHOT.jar"]